name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: bait-lang/setup-bait@main

      - name: Run tests (JS backend)
        run: bait test tasks_test.bt -b js

      - name: Run tests (C backend)
        run: bait test tasks_test.bt -b c

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: bait-lang/setup-bait@main

      - name: Run tests (JS backend)
        run: bait test tasks_test.bt -b js
