name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: bait-lang/setup-bait@main
      - name: Run tests
        run: bait test tasks_test.bt
